version: "2"
services: 
  mutech-iot-mqtt-server:
    build: .
    restart: unless-stopped
    container_name: "iot-mqtt-server"
    ports:
      - '1883:1883'
    volumes:
      - ./configuration:/mqtt/mosquitto/configuration
